maarch-postgres:
  image: postgres:9.6
  container_name: maarch-postgres
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=maarch
  ports: 
    - "5432:5432"

#maarch-webserver:
#  image: phpdockerio/nginx:latest
#  container_name: maarch-webserver
#  volumes:
#      - ..:/var/www/maarch
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#  ports:
#   - "80:80"
#  links:
#   - maarch-php-fpm


maarch-webserver:
  build: .
  dockerfile: apache/Dockerfile
  container_name: maarch-webserver
  volumes:
      - ..:/var/www/maarch
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
  ports:
   - "80:80"
  links:
   - maarch-php-fpm

maarch-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: maarch-php-fpm
  volumes:
    - ..:/var/www/maarch
    - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
  links:
    - maarch-postgres
